version: "3"

services:

  redis:
    image: redis:6.0.7
    container_name: redis-6.0.7
    command: redis-server --port 6379 --requirepass Ol6cReyUgpEAfJ8o --appendonly yes
    ports:
      - "6379:6379"
    restart:
      always
