version: "3"

services:

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --port 6379 --requirepass Ol6cReyUgpEAfJ8o --appendonly yes
    ports:
      - "6379:6379"
    restart:
      always
